# Generated by Django 6.0.3 on 2026-03-28 05:08

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('category', models.CharField(choices=[('1', 'Core Agriculture'), ('2', 'Technical Agriculture'), ('3', 'Home & Community Science')], max_length=1)),
                ('brochure', models.FileField(blank=True, upload_to='brochures/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'college',
                'verbose_name_plural': 'colleges',
                'ordering': ['code'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='universities/')),
            ],
            options={
                'verbose_name': 'university',
                'verbose_name_plural': 'universities',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('1', 'Core Agriculture'), ('2', 'Technical Agriculture'), ('3', 'Home & Community Science')], max_length=1)),
                ('seats_general', models.PositiveIntegerField(default=0)),
                ('seats_sebc', models.PositiveIntegerField(default=0)),
                ('seats_sc', models.PositiveIntegerField(default=0)),
                ('seats_st', models.PositiveIntegerField(default=0)),
                ('seats_ews', models.PositiveIntegerField(default=0)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='colleges.college')),
            ],
            options={
                'verbose_name': 'course',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='college',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colleges', to='colleges.university'),
        ),
        migrations.CreateModel(
            name='CollegeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='colleges.college')),
            ],
            options={
                'verbose_name': 'college Translation',
                'db_table': 'colleges_college_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CourseTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=200)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='colleges.course')),
            ],
            options={
                'verbose_name': 'course Translation',
                'db_table': 'colleges_course_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CutoffMerit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('round_no', models.CharField(choices=[('1', 'Round 1'), ('2', 'Round 2'), ('3', 'Round 3'), ('M', 'Mop-up')], max_length=1)),
                ('student_category', models.CharField(choices=[('OPEN', 'Open / General'), ('SEBC', 'SEBC'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS'), ('PH', 'PH-VH'), ('EX', 'Ex-Serviceman'), ('OB', 'Other Board')], max_length=6)),
                ('last_merit', models.FloatField(help_text='Last admitted merit score this round')),
                ('first_merit', models.FloatField(blank=True, null=True)),
                ('total_admitted', models.PositiveIntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutoffs', to='colleges.course')),
            ],
            options={
                'verbose_name': 'cutoff merit',
                'ordering': ['-year', 'course', 'round_no'],
                'unique_together': {('course', 'year', 'round_no', 'student_category')},
            },
        ),
        migrations.CreateModel(
            name='UniversityTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=20)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='colleges.university')),
            ],
            options={
                'verbose_name': 'university Translation',
                'db_table': 'colleges_university_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
