# Generated by Django 4.2.13 on 2026-04-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegetranslation',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
