# Generated by Django 4.2.13 on 2026-04-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_alter_collegetranslation_district'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'course', 'verbose_name_plural': 'courses'},
        ),
        migrations.AlterModelOptions(
            name='cutoffmerit',
            options={'ordering': ['-year', 'course', 'round_no'], 'verbose_name': 'cutoff merit', 'verbose_name_plural': 'cutoff merits'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.AlterField(
            model_name='college',
            name='brochure',
            field=models.FileField(blank=True, upload_to='brochures/', verbose_name='Brochure PDF'),
        ),
        migrations.AlterField(
            model_name='college',
            name='category',
            field=models.CharField(choices=[('1', 'Core Agriculture'), ('2', 'Technical Agriculture'), ('3', 'Home & Community Science')], max_length=1, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='college',
            name='code',
            field=models.CharField(db_index=True, max_length=10, unique=True, verbose_name='College Code'),
        ),
        migrations.AlterField(
            model_name='college',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='collegetranslation',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='collegetranslation',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='collegetranslation',
            name='name',
            field=models.CharField(max_length=300, verbose_name='College Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Course Code'),
        ),
        migrations.AlterField(
            model_name='course',
            name='seats_ews',
            field=models.PositiveIntegerField(default=0, verbose_name='EWS Seats'),
        ),
        migrations.AlterField(
            model_name='course',
            name='seats_general',
            field=models.PositiveIntegerField(default=0, verbose_name='General Seats'),
        ),
        migrations.AlterField(
            model_name='course',
            name='seats_sc',
            field=models.PositiveIntegerField(default=0, verbose_name='SC Seats'),
        ),
        migrations.AlterField(
            model_name='course',
            name='seats_sebc',
            field=models.PositiveIntegerField(default=0, verbose_name='SEBC Seats'),
        ),
        migrations.AlterField(
            model_name='course',
            name='seats_st',
            field=models.PositiveIntegerField(default=0, verbose_name='ST Seats'),
        ),
        migrations.AlterField(
            model_name='coursetranslation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='cutoffmerit',
            name='first_merit',
            field=models.FloatField(blank=True, null=True, verbose_name='Opening Merit Score'),
        ),
        migrations.AlterField(
            model_name='cutoffmerit',
            name='last_merit',
            field=models.FloatField(verbose_name='Closing Merit Score'),
        ),
        migrations.AlterField(
            model_name='cutoffmerit',
            name='round_no',
            field=models.CharField(choices=[('1', 'Round 1'), ('2', 'Round 2'), ('3', 'Round 3'), ('M', 'Mop-up')], max_length=1, verbose_name='Round'),
        ),
        migrations.AlterField(
            model_name='cutoffmerit',
            name='student_category',
            field=models.CharField(choices=[('OPEN', 'Open / General'), ('SEBC', 'SEBC'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS'), ('PH', 'PH-VH'), ('EX', 'Ex-Serviceman'), ('OB', 'Other Board')], max_length=6, verbose_name='Student Category'),
        ),
        migrations.AlterField(
            model_name='cutoffmerit',
            name='total_admitted',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Admitted'),
        ),
        migrations.AlterField(
            model_name='cutoffmerit',
            name='year',
            field=models.PositiveSmallIntegerField(verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.ImageField(blank=True, upload_to='universities/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='university',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='universitytranslation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='University Name'),
        ),
        migrations.AlterField(
            model_name='universitytranslation',
            name='short_name',
            field=models.CharField(max_length=20, verbose_name='Short Name'),
        ),
    ]
