# Generated by Django 6.0.3 on 2026-03-28 05:08

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_url', models.URLField(blank=True)),
                ('student_categories', models.CharField(blank=True, help_text='Comma-separated: OPEN, SC, ST, SEBC, EWS, GIRL, MINORITY', max_length=100)),
                ('min_percentage', models.FloatField(blank=True, help_text='Min 12th percentage', null=True)),
                ('max_income_lakh', models.FloatField(blank=True, help_text='Max family income in lakhs', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'scholarship',
                'ordering': ['display_order', 'pk'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ScholarshipTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=200)),
                ('eligible_courses', models.TextField(blank=True)),
                ('eligibility_criteria', models.TextField()),
                ('benefits', models.TextField()),
                ('how_to_apply', models.TextField(blank=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='scholarships.scholarship')),
            ],
            options={
                'verbose_name': 'scholarship Translation',
                'db_table': 'scholarships_scholarship_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
