# Generated by Django 4.2.13 on 2026-04-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholarship',
            options={'ordering': ['display_order', 'pk'], 'verbose_name': 'scholarship', 'verbose_name_plural': 'scholarships'},
        ),
        migrations.AlterField(
            model_name='scholarshiptranslation',
            name='benefits',
            field=models.TextField(verbose_name='Benefits'),
        ),
        migrations.AlterField(
            model_name='scholarshiptranslation',
            name='eligibility_criteria',
            field=models.TextField(verbose_name='Eligibility Criteria'),
        ),
        migrations.AlterField(
            model_name='scholarshiptranslation',
            name='eligible_courses',
            field=models.TextField(blank=True, verbose_name='Eligible Courses'),
        ),
        migrations.AlterField(
            model_name='scholarshiptranslation',
            name='how_to_apply',
            field=models.TextField(blank=True, verbose_name='How to Apply'),
        ),
        migrations.AlterField(
            model_name='scholarshiptranslation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='scholarshiptranslation',
            name='notes',
            field=models.CharField(blank=True, max_length=300, verbose_name='Notes'),
        ),
    ]
