# Generated by Django 4.2.13 on 2026-04-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='savedresult',
            name='label',
            field=models.CharField(blank=True, help_text='Optional note', max_length=120),
        ),
    ]
