# Generated by Django 4.2.13 on 2026-04-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_alter_savedresult_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedresult',
            options={},
        ),
        migrations.RemoveField(
            model_name='savedresult',
            name='category',
        ),
        migrations.RemoveField(
            model_name='savedresult',
            name='city',
        ),
        migrations.RemoveField(
            model_name='savedresult',
            name='district',
        ),
        migrations.RemoveField(
            model_name='savedresult',
            name='farming_bonus',
        ),
        migrations.RemoveField(
            model_name='savedresult',
            name='gujcet_marks',
        ),
        migrations.RemoveField(
            model_name='savedresult',
            name='label',
        ),
        migrations.RemoveField(
            model_name='savedresult',
            name='student_category',
        ),
        migrations.RemoveField(
            model_name='savedresult',
            name='subject_group',
        ),
        migrations.RemoveField(
            model_name='savedresult',
            name='theory_total',
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('GEN', 'General'), ('SEBC', 'SEBC'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS')], default='GEN', max_length=10),
        ),
    ]
