# Generated by Django 4.2.13 on 2026-04-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_savedresult_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='category',
        ),
        migrations.AddField(
            model_name='savedresult',
            name='category',
            field=models.CharField(choices=[('1', 'Core Agriculture'), ('2', 'Technical'), ('3', 'Home & Community')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='savedresult',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='savedresult',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='savedresult',
            name='farming_bonus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savedresult',
            name='gujcet_marks',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedresult',
            name='label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='savedresult',
            name='student_category',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedresult',
            name='subject_group',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='savedresult',
            name='theory_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
